[[headers]]
for = "/*"

[headers.values]
  Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline' fonts.googleapis.com; font-src 'self' fonts.gstatic.com https://cdn.jsdelivr.net  data:; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://polyfill.io https://cdn.jsdelivr.net; connect-src 'self' https://www.google-analytics.com" 
          Referrer-Policy = "same-origin"
Strict-Transport-Security = "max-age=15768000"
   X-Content-Type-Options = "nosniff"
          X-Frame-Options = "DENY"
         X-XSS-Protection = "1; mode=block"
             X-Robot-Tags = "all"
